spring:
  application:
    name: webhook
  config:
    import: "configserver:http://host.docker.internal:8888"  # Reemplaza con la URL de tu Config Server si es diferente
  cloud:
    config:
      fail-fast: true
